// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import java.lang.Math.*;

/**
 *
 */
public class DriveCommand extends Command {

    public DriveCommand() {
        requires(Robot.drive);
    }

    @Override
    protected void initialize() {
    }

    @Override
    protected void execute() {
        double strafe = Robot.oi.js1.getRawAxis(0);
        double speed = Robot.oi.js1.getRawAxis(1);
        double rotate = Robot.oi.js1.getRawAxis(2);

        // //Mecanum
        Robot.drive.setMecanumDrive(ramp(strafe), ramp(speed) * -1, ramp(rotate));
    }

    private double ramp(double input){
        //Math.signum(input) * 
        return Math.pow(input, 3);
    }

    @Override
    protected boolean isFinished() {
        return true;
    }

    @Override
    protected void end() {
    }

    @Override
    protected void interrupted() {
    }
}
